### ISSUE TITLE
Doom Plutonia and TNT are wrong

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/libretro-thumbnails#336]
Plutonia snapshot is from TNT and the other way around.
I don't feel like cloning the whole repo to rename them, so if anyone doing some other stuff and feels like doing that too you're welcome!

**Comment by RobLoach** [comment]
> I don't feel like cloning the whole repo to rename them

Been feeling the same thing lately. We may want to consider making [subtree splits](https://encrypted.google.com/search?hl=en&q=subtree%20split) to split the repository up into individual repos. Rather than having them all at `github.com/libretro/libretro-thumbnails` , make a new organization so thumbnails would be at `github.com/libretro-thumbnails/Cave Story`

**Comment by RobLoach** [comment]
Split the repo https://github.com/libretro/libretro-thumbnails/issues/338

**Comment by Tatsuya79** [comment]
Thanks I feel better now!
